---
title: "K-Train"
output: html_document
date: "2026-04-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require(tidyverse)) install.packages("tidyverse")
if (!require(cluster)) install.packages("cluster")
if (!require(factoextra)) install.packages("factoextra")
if (!require(mclust)) install.packages("mclust")

library(tidyverse)
library(cluster)
library(factoextra)
library(mclust)  # for ARI

```

## Load Data
```{r}
df <- read.csv("../data/processed/binary_train.csv")

head(df)
```

## Seperate Features and Target
```{r}
X <- df %>% select(-Diabetes_binary)
y <- df$Diabetes_binary
```

## Scaling
```{r}
X_scaled <- scale(X)
```

## Elbow Method
```{r}
fviz_nbclust(X_scaled, kmeans, method = "wss") +
  ggtitle("Elbow Method for Optimal k")
```

## K-Means Clustering
```{r}
set.seed(42)

kmeans_2 <- kmeans(X_scaled, centers = 2, nstart = 25)
kmeans_3 <- kmeans(X_scaled, centers = 3, nstart = 25)
```

## Cluster Evaluation (ARI)
```{r}
ari_2 <- adjustedRandIndex(y, kmeans_2$cluster)
ari_3 <- adjustedRandIndex(y, kmeans_3$cluster)

ari_2
ari_3
```

## PCA Visualization
```{r}
pca <- prcomp(X_scaled)

pca_data <- data.frame(
  PC1 = pca$x[,1],
  PC2 = pca$x[,2],
  cluster = as.factor(kmeans_3$cluster)
)

ggplot(pca_data, aes(x = PC1, y = PC2, color = cluster)) +
  geom_point(alpha = 0.6, size = 1) +
  ggtitle("K-Means Clusters (k=3)")
```

## Cluster Interpretation
```{r}
df$cluster <- kmeans_3$cluster

cluster_means <- df %>%
  group_by(cluster) %>%
  summarise(across(everything(), mean))

cluster_means
```